defaults:
  - train_transform: simple
  - test_transform: simple
  - aug_transform: augment1
  - aug_strong: augment3
num_classes: 48
batch_size: 160
num_workers: 6
train_path: ${data_dir}/train
test_path: ${data_dir}/test
unlabelled_path: ${data_dir}/unlabelled